"""empty message

Revision ID: 067ccadf16f6
Revises: dd866201a241
Create Date: 2024-03-07 00:31:02.243612

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '067ccadf16f6'
down_revision = 'dd866201a241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
