"""empty message

Revision ID: 1e8021fd11ad
Revises: bef6baf1604d
Create Date: 2024-04-06 22:38:04.736877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e8021fd11ad'
down_revision = 'bef6baf1604d'
branch_labels = None
depends_on = None


def upgrade():
    # rename enum
    op.execute("ALTER TYPE purchasestatus RENAME TO paymentstatus")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('start', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('end', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='paymentstatus'), nullable=False))
    op.drop_column('appointments', 'date')
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'end_time')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'end')
    op.drop_column('appointments', 'start')
    # ### end Alembic commands ###

    # rename enum
    op.execute("ALTER TYP paymentstatus RENAME TO purchasestatus")