"""empty message

Revision ID: 28b7c7771e97
Revises: ca247f381202
Create Date: 2024-03-06 01:13:41.492495

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '28b7c7771e97'
down_revision = 'ca247f381202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_id_uq', 'products', type_='unique')
    op.drop_constraint('storeId_id_uq', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('storeId_id_uq', 'products', ['store_id', 'id'])
    op.create_unique_constraint('product_id_uq', 'products', ['id'])
    # ### end Alembic commands ###
