"""empty message

Revision ID: 2c6f3a8c8dc5
Revises: b571c000ec31
Create Date: 2024-01-14 23:53:55.954422

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2c6f3a8c8dc5'
down_revision = 'b571c000ec31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'id'),
    sa.UniqueConstraint('name', 'store_id', name='product_name_uq')
    )
    op.drop_constraint('addresses_id_key', 'addresses', type_='unique')
    op.drop_constraint('basic_id_key', 'basic', type_='unique')
    op.drop_constraint('stores_id_key', 'stores', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('stores_id_key', 'stores', ['id'])
    op.create_unique_constraint('basic_id_key', 'basic', ['id'])
    op.create_unique_constraint('addresses_id_key', 'addresses', ['id'])
    op.drop_table('products')
    # ### end Alembic commands ###
