"""empty message

Revision ID: 2e52c684ff03
Revises: 7292119e1264
Create Date: 2024-02-25 00:40:48.555082

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2e52c684ff03'
down_revision = '7292119e1264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('shipping_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'shipping_cost')
    # ### end Alembic commands ###
