"""empty message

Revision ID: 3b1c3450b806
Revises: c82969068eb7
Create Date: 2024-03-08 03:47:29.414979

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3b1c3450b806'
down_revision = 'c82969068eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
