"""empty message

Revision ID: 4eb01144c515
Revises: e8d3d4b9f56e
Create Date: 2024-04-23 03:13:14.639421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4eb01144c515'
down_revision = 'e8d3d4b9f56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('animal_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'animal_id')
    # ### end Alembic commands ###
