"""empty message

Revision ID: 5f95e3ac61c5
Revises: f2700709b12b
Create Date: 2024-01-05 13:07:57.521918

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5f95e3ac61c5'
down_revision = 'f2700709b12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
