"""empty message

Revision ID: 70a046347a24
Revises: 592ee8142ab9
Create Date: 2024-01-08 23:00:29.919575

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '70a046347a24'
down_revision = '592ee8142ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'stores', ['id'])
    op.create_unique_constraint(None, 'stores', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_constraint(None, 'stores', type_='unique')
    # ### end Alembic commands ###
