"""empty message

Revision ID: 73a636f19cc3
Revises: 
Create Date: 2024-03-09 20:22:04.697252

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '73a636f19cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('HOUSE', 'APARTMENT', 'OFFICE', 'STOREFRONT', 'OTHER', name='addresstype'), nullable=False),
    sa.Column('apartment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delivery_range_km', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'id'),
    sa.UniqueConstraint('name', 'store_id', name='product_name_uq')
    )
    op.create_table('store_address_link',
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('address_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('address_id', name='store_address_link_address_id_uq')
    )
    op.create_table('product_categories',
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('category', sa.Enum('ALIMENTOS', 'JUGUETES', 'HIGIENE_Y_CUIDADO', 'VIAJES', 'ACCESORIOS', 'SALUD_Y_BIENESTAR', 'CORREAS_Y_COLLARES', 'CUCHAS', 'CAMAS', 'PLATOS_Y_COMEDEROS', name='category'), nullable=False),
    sa.ForeignKeyConstraint(['store_id', 'product_id'], ['products.store_id', 'products.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'product_id', 'category')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    op.drop_table('store_address_link')
    op.drop_table('products')
    op.drop_table('stores')
    op.drop_table('addresses')
    # ### end Alembic commands ###

    # drop category and addresstype enums
    sa.Enum(name='category').drop(op.get_bind())
    sa.Enum(name='addresstype').drop(op.get_bind())
