"""empty message

Revision ID: 756ec68bbe0f
Revises: d0279963e7ee
Create Date: 2024-02-25 00:49:47.240811

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '756ec68bbe0f'
down_revision = 'd0279963e7ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
