"""empty message

Revision ID: 7bcf8b603ef0
Revises: 73a636f19cc3
Create Date: 2024-03-10 02:47:29.203666

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7bcf8b603ef0'
down_revision = '73a636f19cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('percent_off', sa.Numeric(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'percent_off')
    # ### end Alembic commands ###
