"""empty message

Revision ID: 7f47f5e9dc53
Revises: 9bb5f40dcfd6
Create Date: 2024-04-05 00:11:25.873949

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7f47f5e9dc53'
down_revision = '9bb5f40dcfd6'
branch_labels = None
depends_on = None


def upgrade():
    # create enum
    sa.Enum('GROOMING', 'TRAINING', 'WALKING', 'HEALTH', 'CARE', 'OTHER', name='servicecategory').create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category', sa.Enum(name='servicecategory'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'category')
    # ### end Alembic commands ###

    # drop servicecategory enum
    sa.Enum(name='servicecategory').drop(op.get_bind())
