"""empty message

Revision ID: 84ea60421604
Revises: 4eb01144c515
Create Date: 2024-04-27 22:14:38.404930

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '84ea60421604'
down_revision = '4eb01144c515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'price')
    # ### end Alembic commands ###
