"""empty message

Revision ID: 8b48cfa79077
Revises: acde952a0c7f
Create Date: 2024-02-25 23:58:02.943484

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8b48cfa79077'
down_revision = 'acde952a0c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
