"""empty message

Revision ID: 8e1ce62e9296
Revises: a49fe7b654ce
Create Date: 2024-03-09 16:51:11.466793

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8e1ce62e9296'
down_revision = 'a49fe7b654ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('stores', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('stores', sa.Column('delivery_range_km', sa.Float(), nullable=False))
    op.add_column('stores', sa.Column('shipping_cost', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'stores', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_column('stores', 'shipping_cost')
    op.drop_column('stores', 'delivery_range_km')
    op.drop_column('stores', 'description')
    op.drop_column('stores', 'name')
    # ### end Alembic commands ###
