"""empty message

Revision ID: 8f36b4ccd430
Revises: c31c88ee38ca
Create Date: 2024-03-30 21:31:58.208539

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f36b4ccd430'
down_revision = 'c31c88ee38ca'
branch_labels = None
depends_on = None


def upgrade():
    # add 'CREATED' to enum
    op.alter_column('purchases', 'state', new_column_name='status')
    op.execute("ALTER TYPE purchasestatus ADD VALUE 'CREATED' BEFORE 'IN_PROGRESS';")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('payment_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('purchases', sa.Column('buyer', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # remove 'CREATED' from enum
    op.alter_column('purchases', 'status', new_column_name='state')
    op.execute("ALTER TYPE purchasestatus RENAME TO purchasestatus_old;")
    sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='purchasestatus').create(op.get_bind())
    op.execute("ALTER TABLE purchases ALTER COLUMN state TYPE purchasestatus USING state::text::purchasestatus;")
    sa.Enum(name='purchasestatus_old').drop(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'buyer')
    op.drop_column('purchases', 'payment_url')
    # ### end Alembic commands ###
