"""empty message

Revision ID: 9bb5f40dcfd6
Revises: 79055f76d2b6
Create Date: 2024-04-02 07:16:55.902585

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9bb5f40dcfd6'
down_revision = '79055f76d2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('customer_range_km', sa.Float(), nullable=False))
    op.add_column('services', sa.Column('is_home_service', sa.Boolean(), nullable=False))
    op.drop_column('services', 'home_service_range_km')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('home_service_range_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('services', 'is_home_service')
    op.drop_column('services', 'customer_range_km')
    # ### end Alembic commands ###
