"""empty message

Revision ID: a49fe7b654ce
Revises: 3b1c3450b806
Create Date: 2024-03-09 16:42:13.193596

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a49fe7b654ce'
down_revision = '3b1c3450b806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stores_id_fkey', 'stores', type_='foreignkey')
    op.drop_constraint('addresses_id_fkey', 'addresses', type_='foreignkey')
    op.drop_constraint('stores_name_key', 'stores', type_='unique')
    op.drop_table('services')
    op.add_column('stores', sa.Column('address_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_foreign_key(None, 'stores', 'addresses', ['address_id'], ['id'])
    op.drop_column('stores', 'shipping_cost')
    op.drop_column('stores', 'delivery_range_km')
    op.drop_column('stores', 'description')
    op.drop_column('stores', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stores', sa.Column('delivery_range_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('shipping_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.create_foreign_key('stores_id_fkey', 'stores', 'services', ['id'], ['id'])
    op.create_unique_constraint('stores_name_key', 'stores', ['name'])
    op.drop_column('stores', 'address_id')
    op.create_foreign_key('addresses_id_fkey', 'addresses', 'services', ['id'], ['id'])
    op.create_table('services',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('STORE', name='servicetype'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='services_pkey')
    )
    # ### end Alembic commands ###
