"""empty message

Revision ID: acde952a0c7f
Revises: cbf44f985336
Create Date: 2024-02-25 23:30:57.379317

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'acde952a0c7f'
down_revision = 'cbf44f985336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('addresses', 'longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_foreign_key(None, 'addresses', 'services', ['id'], ['id'])
    op.drop_column('addresses', 'postal_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.alter_column('addresses', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=9, scale=6),
               existing_nullable=False)
    op.alter_column('addresses', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=9, scale=6),
               existing_nullable=False)
    # ### end Alembic commands ###
