"""empty message

Revision ID: b571c000ec31
Revises: 00a6e6f5d1c9
Create Date: 2024-01-11 22:50:16.408112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b571c000ec31'
down_revision = '00a6e6f5d1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'addresses', ['id'])
    op.create_unique_constraint(None, 'basic', ['id'])
    op.create_unique_constraint(None, 'stores', ['id'])
    op.drop_column('stores', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('address', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_constraint(None, 'basic', type_='unique')
    op.drop_constraint(None, 'addresses', type_='unique')
    # ### end Alembic commands ###
