"""empty message

Revision ID: c6bcc34cb564
Revises: 8e1ce62e9296
Create Date: 2024-03-09 18:42:10.928509

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c6bcc34cb564'
down_revision = '8e1ce62e9296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_address_link',
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('address_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('address_id', name='store_address_link_address_id_uq')
    )
    op.drop_constraint('stores_address_id_fkey', 'stores', type_='foreignkey')
    op.drop_column('stores', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('stores_address_id_fkey', 'stores', 'addresses', ['address_id'], ['id'])
    op.drop_table('store_address_link')
    # ### end Alembic commands ###
