"""empty message

Revision ID: c82969068eb7
Revises: 067ccadf16f6
Create Date: 2024-03-08 01:34:08.947631

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c82969068eb7'
down_revision = '067ccadf16f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('type', sa.Enum('STORE', name='servicetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('addresses', 'latitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('addresses', 'longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_foreign_key(None, 'addresses', 'services', ['id'], ['id'])
    op.drop_column('addresses', 'postal_code')
    op.add_column('stores', sa.Column('owner_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'stores', 'services', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'owner_id')
    op.add_column('addresses', sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.alter_column('addresses', 'longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=9, scale=6),
               existing_nullable=False)
    op.alter_column('addresses', 'latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=9, scale=6),
               existing_nullable=False)
    op.drop_table('services')
    # ### end Alembic commands ###
