"""empty message

Revision ID: ca247f381202
Revises: 756ec68bbe0f
Create Date: 2024-03-06 01:11:07.264680

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ca247f381202'
down_revision = '756ec68bbe0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories_link',
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('category', sa.Enum('Alimentos', 'Juguetes', 'Higiene y Cuidado', 'Viajes', 'Accesorios', 'Salud y Bienestar', 'Correas y Collares', 'Cuchas', 'Camas', 'Platos y Comederos', name='categoryenum'), nullable=False),
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_id', 'product_id'], ['products.store_id', 'products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category', 'store_id')
    )
    op.create_unique_constraint('product_id_uq', 'products', ['id'])
    op.create_unique_constraint('storeId_id_uq', 'products', ['store_id', 'id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('storeId_id_uq', 'products', type_='unique')
    op.drop_constraint('product_id_uq', 'products', type_='unique')
    op.drop_table('product_categories_link')
    # ### end Alembic commands ###
