"""empty message

Revision ID: d5ce16b886f1
Revises: c49af59982d2
Create Date: 2024-04-09 04:15:50.423547

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd5ce16b886f1'
down_revision = 'c49af59982d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('customer_address_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'customer_address_id')
    # ### end Alembic commands ###
