"""empty message

Revision ID: dd866201a241
Revises: 28b7c7771e97
Create Date: 2024-03-06 23:47:53.480311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd866201a241'
down_revision = '28b7c7771e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('category', sa.Enum('Alimentos', 'Juguetes', 'Higiene_y_Cuidado', 'Viajes', 'Accesorios', 'Salud_y_Bienestar', 'Correas_y_Collares', 'Cuchas', 'Camas', 'Platos_y_Comederos', name='category'), nullable=False),
    sa.ForeignKeyConstraint(['store_id', 'product_id'], ['products.store_id', 'products.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'product_id', 'category')
    )
    op.drop_table('product_categories_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories_link',
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('Alimentos', 'Juguetes', 'Higiene y Cuidado', 'Viajes', 'Accesorios', 'Salud y Bienestar', 'Correas y Collares', 'Cuchas', 'Camas', 'Platos y Comederos', name='categoryenum'), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id', 'product_id'], ['products.store_id', 'products.id'], name='product_categories_link_store_id_product_id_fkey'),
    sa.PrimaryKeyConstraint('product_id', 'category', 'store_id', name='product_categories_link_pkey')
    )
    op.drop_table('product_categories')
    # ### end Alembic commands ###
