"""empty message

Revision ID: e596c3395de3
Revises: 7f47f5e9dc53
Create Date: 2024-04-05 23:33:25.210620

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e596c3395de3'
down_revision = '7f47f5e9dc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_slots', sa.Column('start_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False))
    op.add_column('appointment_slots', sa.Column('end_day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), nullable=False))
    op.drop_column('appointment_slots', 'day_of_week')
    op.add_column('services', sa.Column('timezone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'timezone')
    op.add_column('appointment_slots', sa.Column('day_of_week', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofweek'), autoincrement=False, nullable=False))
    op.drop_column('appointment_slots', 'end_day')
    op.drop_column('appointment_slots', 'start_day')
    # ### end Alembic commands ###
