"""empty message

Revision ID: e8d3d4b9f56e
Revises: 0d265e38316f
Create Date: 2024-04-13 05:17:19.942439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.models.util import TZDateTime

# revision identifiers, used by Alembic.
revision = 'e8d3d4b9f56e'
down_revision = '0d265e38316f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_reviews',
    sa.Column('created_at', TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('service_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'reviewer_id')
    )
    op.create_table('store_reviews',
    sa.Column('created_at', TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'reviewer_id')
    )
    op.create_table('product_reviews',
    sa.Column('created_at', TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', TZDateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('store_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['store_id', 'product_id'], ['products.store_id', 'products.id'], ),
    sa.PrimaryKeyConstraint('store_id', 'product_id', 'reviewer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_reviews')
    op.drop_table('store_reviews')
    op.drop_table('service_reviews')
    # ### end Alembic commands ###
