"""empty message

Revision ID: f2700709b12b
Revises: e9f6ee5b3546
Create Date: 2023-11-21 00:25:01.395328

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "f2700709b12b"
down_revision = "e9f6ee5b3546"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "basic", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "basic", type_="unique")
    # ### end Alembic commands ###
